name: LongThanh.be
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75656
title: Chinees meeneem restaurant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#626169'
    - '#95a7bf'
    - '#060606'
    - '#fdb604'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
