name: LongThanh.be
favicon: null
layout_spectrum: 0.5368993047159165
typography_spectrum: 0.8089577569626272
title: Chinees meeneemrestaurant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9962362695951015
  lightness: 0.35604877257719636
  saturation: 0.3535478920675814
  rhythmicContrast: 0.4479472457896918
purpose: []
