name: LongThanh.be
favicon: null
layout_spectrum: 0.0509
typography_spectrum: 0.21998
title: Chinees meeneem restaurant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7ffff'
    - '#3f4c54'
    - '#a19692'
    - '#280604'
    - '#a42402'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
